### ISSUE TITLE
Weights 

### ISSUE THREAD

**Issue by Skyve1996** [liuzechun/ReActNet#8]
In theory, the weights after BNN should be binarized, but after reproducing the code it is still found to be floating point. Why

**Comment by liuzechun** [comment]
Hi, thanks for the question. In training a BNN model, we use the real-valued latent weights to accumulate the gradient. And in the inference time (as well as the forward pass of the training phase), we use the binarized weight and activations, by taking the sign of the real-valued weights. So the weights stored in the model are the real-valued latent weights, which is binarized in the code in the forward pass. I share the model containing real-valued latent weights because it would be more helpful if readers want to finetune the model. You can obtain the binarized version by taking the sign of it and it will give you the same accuracy. Hope this answers your question.

**Comment by Skyve1996** [comment]
Thanks a lot. Could you give me the code of the binarized version ?

**Comment by liuzechun** [comment]
Sure, I can upload this model for you very soon.

**Comment by Skyve1996** [comment]
Thank you very much.

**Comment by Skyve1996** [comment]
Hello, I'm really sorry to bother you again. But I really want that model. Thank you again

**Comment by liuzechun** [comment]
Hi, sorry for the delay, I uploaded the model with weights stored as exactly -1 and +1 to this repo, replacing the previous models. Please kindly check! Thanks.
